const getAvailableSongs = () => {
    return {
        "11-08-2023": { name: "Over the Rainbow - Harold Arlen"},
        "12-08-2023": { name: "You're Beautiful - James Blunt"},
        "13-08-2023": { name: "Ode to Sleep - Twenty-One Pilots"},
        "14-08-2023": { name: "Car Radio Twenty-One Pilots"},
        "15-08-2023": { name: "That's What Makes you Beautiful - One Direction"},
        "16-08-2024": { name: "10 Things I Hate About You - Leah Kate"},
        "17-08-2024": { name: "50 Ways To Leave Your Lover - Paul Simon"},
        "0": { name: "A Hard Rain's A-Gonna Fall - Bob Dylan"},
        "01": { name: "A Hero's Death - Fontaines D.C."},
        "02": { name: "All American - Mickey Guyton"},
        "03": { name: "All Kinds Of Everything - Dana"},
        "04": { name: "Buy Dirt - Jordan Davis"},
        "05": { name: "Classic - Cam"},
        "06": { name: "Collide - Ed Sheeran"},
        "07": { name: "Come Together - The Beatles"},
        "08": { name: "Country - Angaleena Presley"},
        "09": { name: "Dirty World - The Traveling Wilburys"},
        "010": { name: "Disappointing - John Grant"},
        "011": { name: "Don't Get Better Than That - LoCash"},
        "012": { name: "Don't Let Her - Walker Hayes"},
        "013": { name: "Done Too Soon - Neil Diamond"},
        "014": { name: "Eclipse - Pink Floyd"},
        "015": { name: "Forever After All - Luke Combs"},
        "016": { name: "Happy People - Little Big Town"},
        "017": { name: "Heaven South - Brad Paisley"},
        "018": { name: "I Lived It - Blake Shelton"},
        "019": { name: "I Wish Grandpas Never Died - Riley Green"},
        "020": { name: "Killers Who Are Partying - Madonna"},
        "021": { name: "Last Time for Everything - Brad Paisley"},
        "022": { name: "Let's Do It - Cole Porter"},
        "023": { name: "Lit - Trace Adkins"},
        "024": { name: "Lovin' On You - Luke Combs"},
        "025": { name: "Mellowship Slinky In B Major - Red Hot Chili Peppers"},
        "026": { name: "Metamorphosis - John Grant"},
        "027": { name: "Money - Blake Shelton"},
        "028": { name: "Museum Song - Cast of Barnum"},
        "029": { name: "My Favorite Things - Julie Andrews"},
        "030": { name: "One I Want - Van Halen"},
        "031": { name: "Poster Child - Red Hot Chili Peppers"},
        "032": { name: "Reasons To Be Cheerful Part 3 - Ian Dury & the Blockheads"},
        "033": { name: "Soho (Needless To Say) - Al Stewart"},
        "034": { name: "That's Country Bro - Toby Keith"},
        "035": { name: "That's Entertainment - The Jam"},
        "036": { name: "The Daily Mail Song - Dan & Dan"},
        "037": { name: "Things A Man Oughta Know - Lainey Wilson"},
        "038": { name: "Twelve Days of Christmas - Traditional"},
        "039": { name: "Waiting - Jack Tempchin"},
        "040": { name: "We Didn't Start The Fire - Billy Joel"},
        "041": { name: "Why We Drink - Justin Moore"},
        "042": { name: "Wishlist - Pearl Jam"},
        "043": { name: "You're The Top - Ethel Merman and William Gaxton"},
        "044": { name: "Blacked Out - Chris Young"},
    }
}

export { getAvailableSongs }
