const getAvailableSongs = () => {
    // @todo -- get this to have the name and date inside the object, rather than keying it
    return {
        "0": { name: "A Hard Rain's A-Gonna Fall - Bob Dylan"},
        "01": { name: "A Hero's Death - Fontaines D.C."},
        "02": { name: "All American - Mickey Guyton"},
        "03": { name: "All Kinds Of Everything - Dana"},
        "04": { name: "Buy Dirt - Jordan Davis"},
        "05": { name: "Classic - Cam"},
        "06": { name: "Collide - Ed Sheeran"},
        "07": { name: "Come Together - The Beatles"},
        "08": { name: "Country - Angaleena Presley"},
        "09": { name: "Dirty World - The Traveling Wilburys"},
        "010": { name: "Disappointing - John Grant"},
        "011": { name: "Don't Get Better Than That - LoCash"},
        "012": { name: "Don't Let Her - Walker Hayes"},
        "013": { name: "Done Too Soon - Neil Diamond"},
        "014": { name: "Eclipse - Pink Floyd"},
        "015": { name: "Forever After All - Luke Combs"},
        "016": { name: "Happy People - Little Big Town"},
        "017": { name: "Heaven South - Brad Paisley"},
        "018": { name: "I Lived It - Blake Shelton"},
        "019": { name: "I Wish Grandpas Never Died - Riley Green"},
        "020": { name: "Killers Who Are Partying - Madonna"},
        "021": { name: "Last Time for Everything - Brad Paisley"},
        "022": { name: "Let's Do It - Cole Porter"},
        "023": { name: "Lit - Trace Adkins"},
        "024": { name: "Lovin' On You - Luke Combs"},
        "025": { name: "Mellowship Slinky In B Major - Red Hot Chili Peppers"},
        "026": { name: "Metamorphosis - John Grant"},
        "027": { name: "Money - Blake Shelton"},
        "028": { name: "Museum Song - Cast of Barnum"},
        "029": { name: "My Favorite Things - Julie Andrews"},
        "030": { name: "One I Want - Van Halen"},
        "031": { name: "Poster Child - Red Hot Chili Peppers"},
        "032": { name: "Reasons To Be Cheerful Part 3 - Ian Dury & the Blockheads"},
        "033": { name: "Soho (Needless To Say) - Al Stewart"},
        "034": { name: "That's Country Bro - Toby Keith"},
        "035": { name: "That's Entertainment - The Jam"},
        "036": { name: "The Daily Mail Song - Dan & Dan"},
        "037": { name: "Things A Man Oughta Know - Lainey Wilson"},
        "038": { name: "Twelve Days of Christmas - Traditional"},
        "039": { name: "Waiting - Jack Tempchin"},
        "040": { name: "We Didn't Start The Fire - Billy Joel"},
        "041": { name: "Why We Drink - Justin Moore"},
        "042": { name: "Wishlist - Pearl Jam"},
        "043": { name: "You're The Top - Ethel Merman and William Gaxton"},
        "044": { name: "Blacked Out - Chris Young"},
        "Jack": { name: "Like a Rolling Stone - Bob Dylan" },
        "Jerome": { name: "Satisfaction - The Rolling Stones" },
        "Harvey": { name: "Imagine - John Lennon" },
        "Lena": { name: "What's Going On - Marvin Gaye" },
        "Robert": { name: "Respect - Aretha Franklin" },
        "Ryan": { name: "Good Vibrations - The Beach Boys" },
        "Lee": { name: "Johnny B. Goode - Chuck Berry" },
        "Lucile": { name: "Hey Jude - The Beatles" },
        "Elmer": { name: "Smells Like Teen Spirit - Nirvana" },
        "Daisy": { name: "What'd I Say - Ray Charles" },
        "Devin": { name: "My Generation - The Who" },
        "Alan": { name: "A Change Is Gonna Come - Sam Cooke" },
        "Alice": { name: "Yesterday - The Beatles" },
        "Gabriel": { name: "Blowin' in the Wind - Bob Dylan" },
        "Warren": { name: "London Calling - The Clash" },
        "Marie": { name: "I Want to Hold Your Hand - The Beatles" },
        "Ora": { name: "Purple Haze - Jimi Hendrix" },
        "Beulah": { name: "Maybellene - Chuck Berry" },
        "Richard": { name: "Hound Dog - Elvis Presley" },
        "Louis": { name: "Let It Be - The Beatles" },
        "Violet": { name: "Born to Run - Bruce Springsteen" },
        "Charlie": { name: "Be My Baby - The Ronettes" },
        "Hallie": { name: "In My Life - The Beatles" },
        "Carrie": { name: "People Get Ready - The Impressions" },
        "Rebecca": { name: "God Only Knows - The Beach Boys" },
        "Bernice": { name: "A Day in the Life - The Beatles" },
        "Mittie": { name: "Layla - Derek and the Dominos" },
        "Samuel": { name: "(Sittin on) the Dock of the Bay - Otis Redding" },
        "Addie": { name: "Help! - The Beatles" },
        "Duane": { name: "I Walk the Line - Johnny Cash" },
        "Landon": { name: "Stairway To Heaven - Led Zeppelin" },
        "Alberta": { name: "Sympathy for the Devil - The Rolling Stones" },
        "Herbert": { name: "River Deep - Mountain High - Ike and Tina Turner" },
        "Elsie": { name: "You've Lost That Lovin' Feelin' - The Righteous Brothers" },
        "Chester": { name: "Light My Fire - The Doors" },
        "Francis": { name: "One - U2" },
        "Carlos": { name: "No Woman, No Cry - Bob Marley and the Wailers" },
        "Amanda": { name: "Gimme Shelter - The Rolling Stones" },
        "Rosie": { name: "That'll Be the Day - Buddy Holly and the Crickets" },
        "Allen": { name: "Dancing in the Street - Martha and the Vandellas" },
        "Gordon": { name: "The Weight - The Band" },
        "Francisco": { name: "Waterloo Sunset - The Kinks" },
        "Clara": { name: "Tutti-Frutti - Little Richard" },
        "Philip": { name: "Georgia on My Mind - Ray Charles" },
        "Herman": { name: "Heartbreak Hotel - Elvis Presley" },
        "Ricardo": { name: "Heroes - David Bowie" },
        "Bettie": { name: "Bridge Over Troubled Water - Simon and Garfunkel" },
        "Essie": { name: "All Along the Watchtower - Jimi Hendrix" },
        "Richard": { name: "Hotel California - The Eagles" },
        "Katie": { name: "The Tracks of My Tears - Smokey Robinson and the Miracles" },
        "Anthony": { name: "The Message - Grandmaster Flash and the Furious Five" },
        "Rosie": { name: "When Doves Cry - Prince" },
        "Martin": { name: "Anarchy in the U.K. - The Sex Pistols" },
        "Mabelle": { name: "When a Man Loves a Woman - Percy Sledge" },
        "Ophelia": { name: "Louie Louie - The Kingsmen" },
        "Gene": { name: "Long Tall Sally - Little Richard" },
        "Lewis": { name: "Whiter Shade of Pale - Procol Harum" },
        "Albert": { name: "Billie Jean - Michael Jackson" },
        "Stella": { name: "The Times They Are A-Changin' - Bob Dylan" },
        "Leah": { name: "Let's Stay Together - Al Green" },
        "Myrtie": { name: "Whole Lotta Shakin' Goin On - Jerry Lee Lewis" },
        "Leila": { name: "Bo Diddley - Bo Diddley" },
        "Glen": { name: "For What It's Worth - Buffalo Springfield" },
        "Jacob": { name: "She Loves You - The Beatles" },
        "Isabelle": { name: "Sunshine of Your Love - Cream" },
        "George": { name: "Redemption Song - Bob Marley and the Wailers" },
        "Mabelle": { name: "Jailhouse Rock - Elvis Presley" },
        "Nell": { name: "Tangled Up in Blue - Bob Dylan" },
        "Alejandro": { name: "Crying - Roy Orbison" },
        "Rosa": { name: "Walk On By - Dionne Warwick" },
        "Bill": { name: "California Girls - The Beach Boys" },
        "Noah": { name: "Papa's Got a Brand New Bag - James Brown" },
        "Isabel": { name: "Summertime Blues - Eddie Cochran" },
        "Devin": { name: "Superstition - Stevie Wonder" },
        "Glenn": { name: "Whole Lotta Love - Led Zeppelin" },
        "Elnora": { name: "Strawberry Fields Forever - The Beatles" },
        "Elva": { name: "Mystery Train - Elvis Presley" },
        "Isabelle": { name: "I Got You (I Feel Good) - James Brown" },
        "Blake": { name: "Mr. Tambourine Man - The Byrds" },
        "Shane": { name: "I Heard It Through the Grapevine - Marvin Gaye" },
        "Olive": { name: "Blueberry Hill - Fats Domino" },
        "Phillip": { name: "You Really Got Me - The Kinks" },
        "Emily": { name: "Norwegian Wood (This Bird Has Flown) - The Beatles" },
        "Isabel": { name: "Every Breath You Take - The Police" },
        "Milton": { name: "Crazy - Patsy Cline" },
        "Phoebe": { name: "Thunder Road - Bruce Springsteen" },
        "Joseph": { name: "Ring of Fire - Johnny Cash" },
        "Randall": { name: "My Girl - The Temptations" },
        "Don": { name: "California Dreamin' - The Mamas and The Papas" },
        "Jane": { name: "In the Still of the Nite - The Five Satins" },
        "Jimmy": { name: "Suspicious Minds - Elvis Presley" },
        "Lora": { name: "Blitzkrieg Bop - Ramones" },
        "Inez": { name: "I Still Haven't Found What I'm Looking For - U2" },
        "Ian": { name: "Good Golly, Miss Molly - Little Richard" },
        "Clara": { name: "Blue Suede Shoes - Carl Perkins" },
        "Melvin": { name: "Great Balls of Fire - Jerry Lee Lewis" },
        "Ernest": { name: "Roll Over Beethoven - Chuck Berry" },
        "Cecilia": { name: "Love and Happiness - Al Green" },
        "Gary": { name: "Fortunate Son - Creedence Clearwater Revival" },
        "Maria": { name: "You Can't Always Get What You Want - The Rolling Stones" },
        "Jeanette": { name: "Voodoo Child (Slight Return) - Jimi Hendrix" },
        "Lillie": { name: "Be-Bop-A-Lula - Gene Vincent and His Blue Caps" },
        "Nora": { name: "Hot Stuff - Donna Summer" },
        "Lina": { name: "Living for the City - Stevie Wonder" },
        "Marion": { name: "The Boxer - Simon and Garfunkel" },
        "Fred": { name: "Mr. Tambourine Man - Bob Dylan" },
        "Rosa": { name: "Not Fade Away - Buddy Holly and the Crickets" },
        "Jeanette": { name: "Little Red Corvette - Prince" },
        "Hunter": { name: "Brown Eyed Girl - Van Morrison" },
        "Daniel": { name: "I've Been Loving You Too Long (to Stop Now) - Otis Redding" },
        "Loretta": { name: "I'm So Lonesome I Could Cry - Hank Williams" },
        "Cameron": { name: "That's All Right - Elvis Presley" },
        "Cecelia": { name: "Up on the Roof - The Drifters" },
        "Bessie": { name: "Da Doo Ron Ron (When He Walked Me Home) - The Crystals" },
        "Russell": { name: "You Send Me - Sam Cooke" },
        "Sarah": { name: "Honky Tonk Women - The Rolling Stones" },
        "Amelia": { name: "Take Me to the River  - Al Green" },
        "Lester": { name: "Shout (Parts 1 and 2)] - The Isley Brothers" },
        "Shane": { name: "Go Your Own Way - Fleetwood Mac" },
        "Rosalie": { name: "I Want You Back - The Jackson 5" },
        "Olive": { name: "Stand By Me - Ben E. King" },
        "Craig": { name: "House of the Rising Sun - The Animals" },
        "Tommy": { name: "It's a Man's Man's Man's World - James Brown" },
        "Ella": { name: "Jumpin' Jack Flash - The Rolling Stones" },
        "Harriett": { name: "Will You Love Me Tomorrow - The Shirelles" },
        "Rachel": { name: "Shake, Rattle & Roll - Big Joe Turner" },
        "Betty": { name: "Changes - David Bowie" },
        "Eddie": { name: "Rock & Roll Music - Chuck Berry" },
        "Hester": { name: "Born to Be Wild - Steppenwolf" },
        "Lester": { name: "Maggie May - Rod Stewart" },
        "Elva": { name: "With or Without You - U2" },
        "Louise": { name: "Who Do You Love - Bo Diddley" },
        "Dora": { name: "Won't Get Fooled Again - The Who" },
        "Lottie": { name: "In the Midnight Hour - Wilson Pickett" },
        "Dominic": { name: "While My Guitar Gently Weeps - The Beatles" },
        "Ryan": { name: "Your Song - Elton John" },
        "Leonard": { name: "Eleanor Rigby - The Beatles" },
        "Garrett": { name: "Family Affair - Sly and the Family Stone" },
        "Rodney": { name: "I Saw Her Standing There - The Beatles" },
        "Pauline": { name: "Kashmir - Led Zeppelin" },
        "Nina": { name: "All I Have to Do Is Dream - The Everly Brothers" },
        "Philip": { name: "Please, Please, Please - James Brown" },
        "Mabel": { name: "Purple Rain - Prince" },
        "Edgar": { name: "I Wanna Be Sedated - The Ramones" },
        "Benjamin": { name: "Everyday People - Sly and the Family Stone" },
        "Dominic": { name: "Rock Lobster - The B-52's" },
        "Henry": { name: "Lust for Life - Iggy Pop" },
        "Amy": { name: "Me and Bobby McGee - Janis Joplin" },
        "Garrett": { name: "Cathy's Clown - The Everly Brothers" },
        "Rena": { name: "Eight Miles High - The Byrds" },
        "Lawrence": { name: "Earth Angel - The Penguins" },
        "Dennis": { name: "Foxey Lady - Jimi Hendrix" },
        "Ricky": { name: "A Hard Day's Night - The Beatles" },
        "Jayden": { name: "Rave On - Buddy Holly and the Crickets" },
        "Victoria": { name: "Proud Mary - Creedence Clearwater Revival" },
        "Eddie": { name: "The Sounds of Silence - Simon and Garfunkel" },
        "Claudia": { name: "I Only Have Eyes for You - The Flamingos" },
        "Leonard": { name: "(We're Gonna) Rock Around the Clock - Bill Haley and His Comets" },
        "Florence": { name: "I'm Waiting for the Man - The Velvet Underground" },
        "Jose": { name: "Bring the Noise - Public Enemy" },
        "Lelia": { name: "I Can't Stop Loving You - Ray Charles" },
        "Curtis": { name: "Nothing Compares 2 U - Sinead O'Connor" },
        "Emily": { name: "Bohemian Rhapsody - Queen" },
        "Violet": { name: "Folsom Prison Blues - Johnny Cash" },
        "Ada": { name: "Fast Car - Tracy Chapman" },
        "Eunice": { name: "Lose Yourself  - Eminem" },
        "Charlie": { name: "Let's Get It On - Marvin Gaye" },
        "Hannah": { name: "Papa Was a Rollin' Stone - The Temptations" },
        "Emily": { name: "Losing My Religion - R.E.M." },
        "Bess": { name: "Both Sides Now - Joni Mitchell" },
        "Bertie": { name: "Dancing Queen - Abba" },
        "Adeline": { name: "Dream On - Aerosmith" },
        "Jeanette": { name: "God Save the Queen - The Sex Pistols" },
        "Loretta": { name: "Paint It, Black - The Rolling Stones" },
        "Roger": { name: "I Fought the Law - The Bobby Fuller Four" },
        "Gordon": { name: "Don't Worry Baby - The Beach Boys" },
        "Norman": { name: "Free Fallin' - Tom Petty" },
        "Iva": { name: "September Gurls - Big Star" },
        "Myrtle": { name: "Love Will Tear Us Apart - Joy Division" },
        "Vernon": { name: "Hey Ya! - Outkast" },
        "Emma": { name: "Green Onions - Booker T. and the MG's" },
        "Micheal": { name: "Save the Last Dance for Me - The Drifters" },
        "Caroline": { name: "The Thrill Is Gone - B.B. King" },
        "Scott": { name: "Please Please Me - The Beatles" },
        "Duane": { name: "Desolation Row - Bob Dylan" },
        "Mitchell": { name: "I Never Loved a Man (The Way I Love You) - Aretha Franklin" },
        "Sadie": { name: "Back in Black - AC/DC" },
        "Fannie": { name: "Who'll Stop the Rain - Creedence Clearwater Revival" },
        "Madge": { name: "Stayin' Alive - The Bee Gees" },
        "Martha": { name: "Knocking on Heaven's Door - Bob Dylan" },
        "Polly": { name: "Free Bird - Lynyrd Skynyrd" },
        "Vera": { name: "Wichita Lineman - Glen Campbell" },
        "Scott": { name: "There Goes My Baby - The Drifters" },
        "Isaiah": { name: "Peggy Sue - Buddy Holly" },
        "Isabel": { name: "Maybe - The Chantels" },
        "Jordan": { name: "Sweet Child O' Mine - Guns N' Roses" },
        "Blake": { name: "Don't Be Cruel - Elvis Presley" },
        "Jean": { name: "Hey Joe - Jimi Hendrix" },
        "Miguel": { name: "Flash Light - Parliament" },
        "Theresa": { name: "Loser - Beck" },
        "Francis": { name: "Bizarre Love Triangle - New Order" },
        "Curtis": { name: "Come Together - The Beatles" },
        "Roxie": { name: "Positively 4th Street - Bob Dylan" },
        "Edith": { name: "Try a Little Tenderness - Otis Redding" },
        "Cole": { name: "Lean On Me - Bill Withers" },
        "Sylvia": { name: "Reach Out, I'll Be There - The Four Tops" },
        "Jennie": { name: "Bye Bye Love - The Everly Brothers" },
        "Cecelia": { name: "Gloria - Them" },
        "Adeline": { name: "In My Room - The Beach Boys" },
        "Floyd": { name: "96 Tears - ? and the Mysterians" },
        "Delia": { name: "Caroline, No - The Beach Boys" },
        "Addie": { name: "1999 - Prince" },
        "Helen": { name: "Your Cheatin' Heart - Hank Williams" },
        "Lela": { name: "Rockin' in the Free World - Neil Young" },
        "Eula": { name: "Sh-Boom - The Chords" },
        "Beulah": { name: "Do You Believe in Magic - The Lovin' Spoonful" },
        "Clarence": { name: "Jolene - Dolly Parton" },
        "Effie": { name: "Boom Boom - John Lee Hooker" },
        "Winnie": { name: "Spoonful - Howlin' Wolf" },
        "Susan": { name: "Walk Away Renee - The Left Banke" },
        "Rachel": { name: "Walk on the Wild Side - Lou Reed" },
        "Amanda": { name: "Oh, Pretty Woman - Roy Orbison" },
        "Lily": { name: "Dance to the Music - Sly and the Family Stone" },
        "Georgia": { name: "Good Times - Chic" },
        "Mathilda": { name: "Hoochie Coochie Man - Muddy Waters" },
        "Estelle": { name: "Moondance - Van Morrison" },
        "Lucas": { name: "Fire and Rain - James Taylor" },
        "Alvin": { name: "Should I Stay or Should I Go - The Clash" },
        "Walter": { name: "Mannish Boy - Muddy Waters" },
        "Roger": { name: "Just Like a Woman - Bob Dylan" },
        "Celia": { name: "Sexual Healing - Marvin Gaye" },
        "Sam": { name: "Only the Lonely - Roy Orbison" },
        "Janie": { name: "We Gotta Get Out of This Place - The Animals" },
        "Minerva": { name: "I'll Feel a Whole Lot Better - The Byrds" },
        "Cody": { name: "I Got a Woman - Ray Charles" },
        "Victoria": { name: "Everyday - Buddy Holly and the Crickets" },
        "Kenneth": { name: "Planet Rock - Afrika Bambaataa and the Soul Sonic Force" },
        "Carolyn": { name: "I Fall to Pieces - Patsy Cline" },
        "Madge": { name: "The Wanderer - Dion" },
        "Steven": { name: "Son of a Preacher Man - Dusty Springfield" },
        "Jeffery": { name: "Stand! - Sly and the Family Stone" },
        "Hester": { name: "Rocket Man - Elton John" },
        "Dale": { name: "Love Shack - The B-52's" },
        "Sophie": { name: "Gimme Some Lovin' - The Spencer Davis Group" },
        "Steve": { name: "The Night They Drove Old Dixie Down - The Band" },
        "Blake": { name: "(Your Love Keeps Lifting Me) Higher and Higher - Jackie Wilson" },
        "Allie": { name: "Hot Fun in the Summertime - Sly and the Family Stone" },
        "Jesse": { name: "Rappers Delight - The Sugarhill Gang" },
        "Randy": { name: "Chain of Fools - Aretha Franklin" },
        "Norman": { name: "Paranoid - Black Sabbath" },
        "Mayme": { name: "Mack the Knife - Bobby Darin" },
        "Jimmy": { name: "Money Honey - The Drifters" },
        "Christian": { name: "All the Young Dudes - Mott the Hoople" },
        "Jesse": { name: "Highway to Hell - AC/DC" },
        "Eric": { name: "Heart of Glass - Blondie" },
        "Sally": { name: "Paranoid Android - Radiohead" },
        "Jay": { name: "Wild Thing - The Troggs" },
        "Ruby": { name: "I Can See for Miles - The Who" },
        "Christopher": { name: "Hallelujah - Jeff Buckley" },
        "Mathilda": { name: "Oh, What a Night - The Dells" },
        "Dean": { name: "Higher Ground - Stevie Wonder" },
        "Jackson": { name: "Ooo Baby Baby - Smokey Robinson" },
        "Cecilia": { name: "He's a Rebel - The Crystals" },
        "Russell": { name: "Sail Away - Randy Newman" },
        "Caroline": { name: "Tighten Up - Archie Bell and the Drells" },
        "Edith": { name: "Walking in the Rain - The Ronettes" },
        "Billy": { name: "Personality Crisis - New York Dolls" },
        "Andrew": { name: "Sunday Bloody Sunday - U2" },
        "Cornelia": { name: "Roadrunner - The Modern Lovers" },
        "Mollie": { name: "He Stopped Loving Her Today - George Jones" },
        "Hilda": { name: "Sloop John B - The Beach Boys" },
        "Francis": { name: "Sweet Little Sixteen - Chuck Berry" },
        "Jeremiah": { name: "Something - The Beatles" },
        "Emma": { name: "Somebody to Love - Jefferson Airplane" },
        "Tyler": { name: "Born in the U.S.A. - Bruce Springsteen" },
        "Christopher": { name: "I'll Take You There - The Staple Singers" },
        "Douglas": { name: "Ziggy Stardust - David Bowie" },
        "Rodney": { name: "Pictures of You - The Cure" },
        "Chris": { name: "Chapel of Love - The Dixie Cups" },
        "Minnie": { name: "Ain't No Sunshine - Bill Withers" },
        "Cole": { name: "You Are the Sunshine of My Life - Stevie Wonder" },
        "Adam": { name: "Help Me - Joni Mitchell" },
        "Vernon": { name: "Call Me - Blondie" },
        "Jeremy": { name: "(What's So Funny 'Bout) Peace Love and Understanding? - Elvis Costello and the Attractions" },
        "Samuel": { name: "Smoke Stack Lightning - Howlin' Wolf" },
        "Joel": { name: "Summer Babe - Pavement" },
        "Joshua": { name: "Walk This Way - Run-DMC" },
        "Vincent": { name: "Money (That's What I Want) - Barrett Strong" },
        "Gertrude": { name: "Can't Buy Me Love - The Beatles" },
        "Estella": { name: "Stan - Eminem featuring Dido" },
        "Elnora": { name: "She's Not There - The Zombies" },
        "Andrew": { name: "Train in Vain - The Clash" },
        "Logan": { name: "Tired of Being Alone - Al Green" },
        "Ronnie": { name: "Black Dog - Led Zeppelin" },
        "Albert": { name: "Street Fighting Man - The Rolling Stones" },
        "Mario": { name: "Get Up, Stand Up - Bob Marley and the Wailers" },
        "Marian": { name: "Heart of Gold - Neil Young" },
        "Callie": { name: "One Way or Another - Blondie" },
        "Lucile": { name: "Sign 'O' the Times - Prince" },
        "Genevieve": { name: "Like a Prayer - Madonna" },
        "Garrett": { name: "Do Ya Think I'm Sexy? - Rod Stewart" },
        "Eva": { name: "Blue Eyes Crying In the Rain - Willie Nelson" },
        "Anne": { name: "Ruby Tuesday - The Rolling Stones" },
        "Sadie": { name: "With a Little Help From My Friends - The Beatles" },
        "Johanna": { name: "Say It Loud, I'm Black and Proud - James Brown" },
        "Albert": { name: "That's Entertainment - The Jam" },
        "Pearl": { name: "Why Do Fools Fall In Love - Frankie Lymon and the Teenagers" },
        "Elsie": { name: "Lonely Teardrops - Jackie Wilson" },
        "Marian": { name: "What's Love Got To Do With It - Tina Turner" },
        "Jesse": { name: "Iron Man - Black Sabbath" },
        "Marc": { name: "Wake Up Little Susie - The Everly Brothers" },
        "Francis": { name: "In Dreams - Roy Orbison" },
        "Joseph": { name: "I Put a Spell on You - Screamin' Jay Hawkins" },
        "Jerome": { name: "Comfortably Numb - Pink Floyd" },
        "Estella": { name: "Don't Let Me Be Misunderstood - The Animals" },
        "Belle": { name: "Wish You Were Here - Pink Floyd" },
        "Cameron": { name: "Many Rivers to Cross - Jimmy Cliff" },
        "Lewis": { name: "Alison - Elvis Costello" },
        "Lydia": { name: "School's Out - Alice Cooper" },
        "Jeanette": { name: "Heartbreaker - Led Zeppelin" },
        "Gene": { name: "Cortez the Killer - Neil Young" },
        "Christopher": { name: "Fight the Power - Public Enemy" },
        "Kyle": { name: "Dancing Barefoot - Patti Smith Group" },
        "Lou": { name: "Baby Love - The Supremes" },
        "Christina": { name: "Good Lovin' - The Young Rascals" },
        "Evelyn": { name: "Get Up (I Feel Like Being a) Sex Machine - James Brown" },
        "Douglas": { name: "For Your Precious Love - Jerry Butler and the Impressions" },
        "Mamie": { name: "The End - The Doors" },
        "Sallie": { name: "That's the Way of the World - Earth, Wind and Fire" },
        "Eddie": { name: "We Will Rock You - Queen" },
        "Edward": { name: "I Can't Make You Love Me - Bonnie Raitt" },
        "Anne": { name: "Subterranean Homesick Blues - Bob Dylan" },
        "Martha": { name: "Spirit in the Sky - Norman Greenbaum" },
        "Alex": { name: "Wild Horses - The Rolling Stones" },
        "Susie": { name: "Sweet Jane - The Velvet Underground" },
        "Lucinda": { name: "Walk This Way - Aerosmith" },
        "Gregory": { name: "Beat It - Michael Jackson" },
        "Roy": { name: "Maybe I'm Amazed - Paul McCartney" },
        "Francis": { name: "You Keep Me Hanging On - The Supremes" },
        "Trevor": { name: "Baba O'Riley - The Who" },
        "Phoebe": { name: "The Harder They Come - Jimmy Cliff" },
        "Lettie": { name: "Runaround Sue - Dion" },
        "Zachary": { name: "Jim Dandy - Lavern Baker" },
        "Cornelia": { name: "Piece of My Heart - Big Brother and the Holding Company" },
        "Millie": { name: "La Bamba - Ritchie Valens" },
        "Tommy": { name: "California Love - Dr. Dre and 2Pac" },
        "Travis": { name: "Candle in the Wind - Elton John" },
        "Lenora": { name: "That Lady (Part 1 and 2) - The Isley Brothers" },
        "Tillie": { name: "Spanish Harlem - Ben E. King" },
        "Hattie": { name: "The Locomotion - Little Eva" },
        "Sophia": { name: "The Great Pretender - The Platters" },
        "Charlotte": { name: "All Shook Up - Elvis Presley" },
        "Christine": { name: "Tears in Heaven - Eric Clapton" },
        "Glen": { name: "Watching the Detectives - Elvis Costello" },
        "Marion": { name: "Bad Moon Rising - Creedence Clearwater Revival" },
        "Phoebe": { name: "Sweet Dreams (Are Made of This) - Eurythmics" },
        "Gavin": { name: "Little Wing - Jimi Hendrix" },
        "Madge": { name: "Nowhere to Run - Martha and the Vandellas" },
        "Linnie": { name: "Got My Mojo Working - Muddy Waters" },
        "Bruce": { name: "Killing Me Softly With His Song - Roberta Flack" },
        "Mabel": { name: "Complete Control - The Clash" },
        "Lucile": { name: "All You Need Is Love - The Beatles" },
        "Nancy": { name: "The Letter - The Box Tops" },
        "Lewis": { name: "Highway 61 Revisited - Bob Dylan" },
        "Janie": { name: "Unchained Melody - The Righteous Brothers" },
        "Isabelle": { name: "How Deep Is Your Love - The Bee Gees" },
        "Hunter": { name: "White Room - Cream" },
        "Amanda": { name: "Personal Jesus - Depeche Mode" },
        "Teresa": { name: "I'm A Man - Bo Diddley" },
        "Juan": { name: "The Wind Cries Mary - Jimi Hendrix" },
        "Abbie": { name: "I Can't Explain - The Who" },
        "Nathaniel": { name: "Marquee Moon - Television" },
        "Blake": { name: "Wonderful World - Sam Cooke" },
        "Bettie": { name: "Brown Eyed Handsome Man - Chuck Berry" },
        "Gregory": { name: "Another Brick in the Wall Part 2 - Pink Floyd" },
        "Daniel": { name: "Fake Plastic Trees - Radiohead" },
        "Bradley": { name: "Hit the Road Jack - Ray Charles" },
        "Madge": { name: "Pride (In The Name of Love) - U2" },
        "Harvey": { name: "Radio Free Europe - R.E.M." },
        "Katharine": { name: "Goodbye Yellow Brick Road - Elton John" },
        "Cecelia": { name: "Tell It Like It Is - Aaron Neville" },
        "Leona": { name: "Bitter Sweet Symphony - The Verve" },
        "Annie": { name: "Whipping Post - The Allman Brothers Band" },
        "Cory": { name: "Ticket to Ride - The Beatles" },
        "Carlos": { name: "Ohio - Crosby, Stills, Nash and Young" },
        "Matilda": { name: "I Know You Got Soul - Eric B and Rakim" },
        "Katharine": { name: "Tiny Dancer - Elton John" },
        "Franklin": { name: "Roxanne - The Police" },
        "Howard": { name: "Just My Imagination - The Temptations" },
        "Wesley": { name: "Baby I Need Your Loving - The Four Tops" },
        "Aaron": { name: "Band of Gold - Freda Payne" },
        "Estelle": { name: "O-o-h Child - The Five Stairsteps" },
        "Emily": { name: "Summer in the City - The Lovin' Spoonful" },
        "Norman": { name: "Can't Help Falling in Love - Elvis Presley" },
        "Jordan": { name: "Remember (Walkin' in the Sand) - The Shangri-Las" },
        "Jane": { name: "Thirteen - Big Star" },
        "Lizzie": { name: "(Don't Fear) the Reaper - Blue Oyster Cult" },
        "Alfred": { name: "Sweet Home Alabama - Lynyrd Skynyrd" },
        "Cecilia": { name: "Enter Sandman - Metallica" },
        "Barbara": { name: "Kicks - Paul Revere and the Raiders" },
        "Noah": { name: "Tonight's the Night - The Shirelles" },
        "Stephen": { name: "Thank You (Falettinme Be Mice Elf Agin) - Sly & the Family Stone" },
        "Mike": { name: "C'mon Everybody - Eddie Cochran" },
        "Louis": { name: "Visions of Johanna - Bob Dylan" },
        "Esther": { name: "We've Only Just Begun - The Carpenters" },
        "Nina": { name: "I Believe I Can Fly - R. Kelly" },
        "Marvin": { name: "In Bloom - Nirvana" },
        "Jerome": { name: "Sweet Emotion - Aerosmith" },
        "Lee": { name: "Crossroads - Cream" },
        "Virginia": { name: "Monkey Gone to Heaven - Pixies" },
        "Bill": { name: "I Feel Love - Donna Summer" },
        "Sophie": { name: "Ode to Billie Joe - Bobbie Gentry" },
        "Nancy": { name: "The Girl Can't Help It - Little Richard" },
        "Brandon": { name: "Young Blood - The Coasters" },
        "Jeffery": { name: "I Can't Help Myself - The Four Tops" },
        "Roger": { name: "The Boys of Summer - Don Henley" },
        "Danny": { name: "Fuck tha Police - N.W.A." },
        "Mike": { name: "Suite: Judy Blue Eyes - Crosby, Stills and Nash" },
        "Roger": { name: "Nuthin' But a 'G' Thang - Dr. Dre" },
        "Lily": { name: "It's Your Thing - The Isley Brothers" },
        "Lois": { name: "Piano Man - Billy Joel" },
        "Douglas": { name: "Lola - The Kinks" },
        "Myrtle": { name: "Blue Suede Shoes - Elvis Presley" },
        "Ryan": { name: "Tumbling Dice - The Rolling Stones" },
        "Angel": { name: "William, It Was Really Nothing - The Smiths" },
        "Alan": { name: "Smoke on the Water - Deep Purple" },
        "Norman": { name: "New Year's Day - U2" },
        "Sylvia": { name: "Devil With a Blue Dress On - Mitch Ryder and the Detroit Wheels" },
        "Emma": { name: "Everybody Needs Somebody to Love - Solomon Burke" },
        "Nora": { name: "White Man in Hammersmith Palais - The Clash" },
        "Jeffrey": { name: "Ain't It a Shame - Fats Domino" },
        "Marian": { name: "Midnight Train to Georgia - Gladys Knight and the Pips" },
        "Myrtle": { name: "Ramble On - Led Zeppelin" },
        "Isaiah": { name: "Mustang Sally - Wilson Pickett" },
        "Ollie": { name: "Beast of Burden - The Rolling Stones" },
        "Maurice": { name: "Alone Again Or - Love" },
        "Ruby": { name: "Love Me Tender - Elvis Presley" },
        "Caleb": { name: "I Wanna Be Your Dog - The Stooges" },
        "Adam": { name: "Pink Houses - John Cougar Mellencamp" },
        "Harold": { name: "Push It - Salt-n-Pepa" },
        "Myrtle": { name: "Come Go With Me - The Del-Vikings" },
        "Gavin": { name: "Keep a Knockin' - Little Richard" },
        "Callie": { name: "I Shot the Sheriff - Bob Marley and the Whailers" },
        "Kathryn": { name: "I Got You Babe - Sonny and Cher" },
        "Floyd": { name: "Come As You Are - Nirvana" },
        "Alma": { name: "Pressure Drop - Toot and the Maytals" },
        "Norman": { name: "Leader of the Pack - The Shangri-Las" },
        "Nannie": { name: "Heroin - The Velvet Underground" },
        "Lydia": { name: "Penny Lane - The Beatles" },
        "Lucas": { name: "By the Time I Get to Phoenix - Glem Campbell" },
        "Alvin": { name: "The Twist - Chubby Checker" },
        "Viola": { name: "Cupid - Sam Cooke" },
        "Rodney": { name: "Paradise City - Guns n' Roses" },
        "Gavin": { name: "My Sweet Lord - George Harrison" },
        "Ruth": { name: "All Apologies - Nirvana" },
        "Cameron": { name: "Stagger Lee - Lloyd Price" },
        "Brent": { name: "Sheena Is a Punk Rocker - Ramones" },
        "Marion": { name: "Soul Man - Sam and Dave" },
        "Bertha": { name: "Rollin' Stone - Muddy Waters" },
        "Phillip": { name: "One Fine Day - The Chiffons" },
        "Pauline": { name: "Kiss - Prince" },
        "Eleanor": { name: "Respect Yourself - The Staple Singers" },
        "Todd": { name: "Rain - The Beatles" },
        "Ronald": { name: "Standing in the Shadows of Love - The Four Tops" },
        "Joel": { name: "Surrender - Cheap Trick" },
        "Noah": { name: "Runaway - Del Shannon" },
        "Hilda": { name: "Welcome to the Jungle - Guns n' Roses" },
        "Carrie": { name: "Search and Destroy - The Stooges" },
        "Gene": { name: "It's Too Late - Carole King" },
        "Martha": { name: "Free Man in Paris - Joni Mitchell" },
        "Henrietta": { name: "On the Road Again - Willie Nelson" },
        "John": { name: "Where Did Our Love Go - The Supremes" },
        "Hallie": { name: "Do Right Woman, Do Right Man - Aretha Franklin" },
        "Bertha": { name: "One Nation Under a Groove - Funkadelic" },
        "Douglas": { name: "Sabotage - Beastie Boys" },
        "Paul": { name: "I Want to Know What Love Is - Foreigner" },
        "Martha": { name: "Super Freak - Rick James" },
        "Ronnie": { name: "White Rabbit - Jefferson Airplane" },
        "Isabelle": { name: "Lady Marmalade - Labelle" },
        "Landon": { name: "Into the Mystic - Van Morrison" },
        "Hallie": { name: "Young Americans - David Bowie" },
        "Mollie": { name: "I'm Eighteen - Alice Cooper" },
        "Carolyn": { name: "Just Like Heaven - The Cure" },
        "Maurice": { name: "I Love Rock 'N Roll - Joan Jett" },
        "Olivia": { name: "Graceland - Paul Simon" },
        "Mitchell": { name: "How Soon Is Now? - The Smiths" },
        "Mario": { name: "Under the Boardwalk - The Drifters" },
        "Mollie": { name: "Rhiannon (Will You Ever Win) - Fleetwood Mac" },
        "Todd": { name: "I Will Survive - Gloria Gaynor" },
        "Dale": { name: "Brown Sugar - The Rolling Stones" },
        "Carolyn": { name: "You Don't Have to Say You Love Me - Dusty Springfield" },
        "Devin": { name: "Running on Empty - Jackson Browne" },
        "Maude": { name: "Then He Kissed Me - The Crystals" },
        "Gene": { name: "Desperado - The Eagles" },
        "Jared": { name: "Shop Around - Smokey Robinson and the Miracles" },
        "Ernest": { name: "Miss You - The Rolling Stones" },
        "Isaac": { name: "Buddy Holly - Weezer" },
        "Christian": { name: "Rainy Night in Georgia - Brook Benton" },
        "Ann": { name: "The Boys Are Back in Town - Thin Lizzy" },
        "Gerald": { name: "More Than a Feeling - Boston" },
        "11-08-2023": { name: "Over the Rainbow - Harold Arlen"},
        "12-08-2023": { name: "Can you feel the love tonight - Elton John"},
        "13-08-2023": { name: "Hello - Adele" },
        "14-08-2023": { name: "You're Beautiful - James Blunt"},
        "15-08-2023": { name: "I love rock and roll - Joan Jett & the Blackhearts"},
        "16-08-2023": { name: "Perfect - Ed Sheeran"},
        "17-08-2023": { name: "Remember Me - Robert Lopez and Kristen Anderson-Lopez"},
        "18": { name: "That's What Makes you Beautiful - One Direction"},
        "19": { name: "10 Things I Hate About You - Leah Kate"},
        "20": { name: "50 Ways To Leave Your Lover - Paul Simon"},
        "21": { name: "Ode to Sleep - Twenty-One Pilots"},
        "22": { name: "Car Radio - Twenty-One Pilots"},
    }
}

export { getAvailableSongs }
